version: '3'
services:
    mongo:    
        image: "mongo:4.4.19-rc2"
        container_name: mongo_test
        restart: always
        ports: 
            - 27017:27017
        volumes:
            - ./container/data:/data/db
    app:
        build: .
        container_name: server_test
        ports:
            - 8082:8080
volumes:
    mongodb:
